name: orderstage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/splash.png
  - assets/images/empty_logo.png
  - assets/images/bg.png
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Black.ttf
        - asset: assets/font/Tajawal-Bold.ttf
        - asset: assets/font/Tajawal-ExtraBold.ttf
        - asset: assets/font/Tajawal-ExtraLight.ttf
        - asset: assets/font/Tajawal-Light.ttf
        - asset: assets/font/Tajawal-Medium.ttf
        - asset: assets/font/Tajawal-Regular.ttf